# .github/workflows/test.yml
name: Run Bun Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      RUN_INTEGRATION_TESTS: "true"  # Remove or set to false if you prefer not to run integration tests by default.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests with DOM globals and React 18 support
        run: bun test --preload ./frontend/test-setup.ts
